version: '3.8'

services:
  # CLIENTE WEB 2: FLASK 
  web-interno:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_BASE_URL=http://api_central:8000/api/v1
      - FLASK_DEBUG=1
    volumes:
      - .:/app

  # CLIENTE WEB 1: LARAVEL 
  web-externo:
    build: 
      context: ./laravel_app
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./laravel_app:/app
    environment:
      - API_BASE_URL=http://api_central:8000/api/v1